Bump mockgen
This should fix the following error we see in the dependabot PRs after
switching to go 1.25:

    Error: ../../../go/pkg/mod/golang.org/x/tools@v0.22.0/internal/tokeninternal/tokeninternal.go:64:9: invalid array length -delta * delta (constant -256 of type int64)