Update installation method in getting started docs
The previously documented method for deploying ORC does not work with v2
as it is missing a kustomization file:

    $ export ORC_RELEASE="https://github.com/k-orc/openstack-resource-controller/dist?ref=v2.0.2"
    $ kubectl apply --server-side -k $ORC_RELEASE
    error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/tmp/kustomize-50497731/dist'

Instead, point to the `install.yaml` from the latest released artifact.